version: 0.0
os: linux
files:
  - source: build/libs/backend-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/backend
    overwrite: yes
  - source: appspec.yml
    destination: /home/ec2-user/backend/
    overwrite: yes
  - source: scripts
    destination: /home/ec2-user/backend/
    overwrite: yes
  - source: src/main/resources/logback.xml
    destination: /home/ec2-user/backend/
    overwrite: yes
  - source: src/main/resources/info-appender.xml
    destination: /home/ec2-user/backend/
    overwrite: yes
  - source: src/main/resources/error-appender.xml
    destination: /home/ec2-user/backend/
    overwrite: yes
  - source: src/main/resources/warn-appender.xml
    destination: /home/ec2-user/backend/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 240
      runas: ec2-user
