spring:
  security:
    user:
      name: admin
      password: sajfds8gf-ahfdsfa9-asdfsadfg-gfdag
      
    oauth2:
      client:
        registration:
          kakao:
            client-id: 78c38ed072300eb731d2672e22f28c05
            client-secret: zMIUg2A0CykWkfLQP4mV1RgFr7B9iJ5v
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cors:
    allowed-origins: "http://localhost:8080,http://localhost:3000,http://43.200.29.96"
    allowed-methods: GET, POST, PUT, DELETE
    allowed-headers-1: "Authorization"
    allowed-headers-2: "Content-Type"
    exposed-headers: "*"
    allow-credentials: true


jwt:
  secretKey: asdfsdgguiaeghrfjbehjfbjhbaesiufuhifbjsdbahjdbvjcnhziohcvjsdajkfbjkedbesuibvsdvnjkdnfkansdoivhjfdpvhjadfihviehwjkfberjfbandbfvjckbxzjkb
  access:
    expiration: 1800000
  refresh:
    expiration: 604800000
